swagger: "2.0"
info:
  description: "API specification for the  {{ cookiecutter.service_name }}"
  version: "1.0.0"
  title: "{{ cookiecutter.service_name }}"
host: api.ft.com
schemes:
  - http
  - https
basePath: /

paths:
  /__gtg:
    get:
      summary: GoodToGo
      description: _describe what are the mechanics of the gtg_
      responses:
        200:
          description: OK
        500:
          description: Internal Error
        503:
          description: Not good to go
  /__build-info:
    get:
      summary: Build-Info
      description: Gives details of the version of the {{ cookiecutter.service_name }} service
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/BuildInfo'
        500:
          description: Internal Error
definitions:
  BuildInfo:
    properties:
      version:
        type: string
        description: Build tag
      repository:
        type: string
        description: Source code repository location
      revision:
        type: string
        description: Revision
      builder:
        type: string
        description: What built this service
      datetime:
        type: integer
        description: Timestamp